### ISSUE TITLE
Message Limit and Possible Cool down for !phon command

### ISSUE THREAD

**Issue by LukeG294** [brainbotdev/brainbot#54] opened 2020-10-09 04:38 UTC
**Is your feature request related to a problem? Please describe.**
Yes, this function is prone to spam.

**Describe the solution you'd like**
A cool down and/or message character limit feature.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bsoyka** [comment] 2020-10-09 04:39
Duplicate of #52

**Closed by bsoyka** 2020-10-09 04:39 UTC
Labels: duplicate, enhancement
